Privatix/dapp-installer

- dapp/dapp.go
- dapp/dapp_unix.go
- dapp/dapp_windows.go
- data/data.go
- dbengine/dbengine.go
- util/misc.go
- util/misc_test.go
> available ports to dappctrl.config

- util/misc.go
> fix DB not copied during update

- util/misc_unix.go
- util/misc_windows.go
> fix RAM of VM can't be detected

- command/command.go
- command/funcs.go
- dapp/dapp.go
- data/data.go
> write app version

- statik/templates/torrc.tpl
- tor/tor.go
> creates hidden_service folder

- dapp-installer.config.json
- dapp/dapp.go
> sets wsEndpoint to dappgui settings

- command/command.go
- command/const.go
- command/funcs.go
- env/env.go
- main.go
- tool/winsvc/service.go
> create env store

- dapp/dapp_windows.go
> restart service after failure

- dapp/dapp_windows.go
> dappctrl service dependencies

- dapp/dapp.go
- tor/tor.go
> add Tor target port to config

- command/funcs.go
- dapp/dapp.go
- env/env.go
- scripts/build.sh
> add unique machine id to configs

- command/funcs.go
- util/misc_unix.go
> removes extended attributes

- product/product.go
- util/misc_unix.go
- util/misc_windows.go
Exception details when executing an external command.
> detailed log

- dapp/dapp.go
- dapp/misc.go
> sets external IP to PayServer

- ubuntu/GUI-Initializer/sources/initializer.py
- ubuntu/GUI-Initializer/sources/welcomePage.py
not serious calligraphic changes
> bugfix gui

- util/misc_unix.go
> overwrite  existing  files

- command/funcs.go
- dapp/dapp_windows.go
- tor/tor.go
- tor/tor_darwin.go
- tor/tor_windows.go
- unix/daemon_linux.go
- util/misc_windows.go
> fixed tor service creation on windows 7

- dapp/dapp.go
- dapp/dapp_unix.go
- dapp/dapp_windows.go
- util/misc_unix.go
- util/misc_windows.go
> removes the logic to create a shortcut

- tool/ps-runner/.gitignore
- tool/ps-runner/README.md
- tool/ps-runner/embed/ps-runner.exe.manifest
- tool/ps-runner/main.go
- tool/ps-runner/ps-runner.config.json
- tool/ps-runner/versioninfo.json
ps-runner was moved from privatix repo
> ps-runner was moved from privatix repo

- scripts/win/toml.ps1
- write to "Gopkg.toml" directly
> simplify toml generation

- dapp/dapp.go
- dapp/dapp_unix.go
- dapp/dapp_windows.go
Resolves Privatix/privatix#78.
> fix clear gui storage on Windows

- dbengine/dbengine.go
> fix database cluster initialization

- product/proc.go
> calculate template fields

- product/proc.go
Resolves Privatix/privatix#129
> compress schema json before computing hash

- installbuilder/project/Privatix.xml
- installbuilder/project/en.lng
expected to be merged after #99
> add dapp-supervisor to bitrock builder
